package writory.exception.authentication

class UserFoundException : RuntimeException()
